# Generated by Django 5.2 on 2025-09-08 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('availability_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='offline', max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('availability_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(default=4.5)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='therapist_photos/')),
                ('fee', models.IntegerField(default=800)),
                ('profile_description', models.TextField(blank=True)),
                ('expertise_areas', models.JSONField(blank=True, default=list, null=True)),
                ('specializations', models.JSONField(blank=True, default=list, null=True)),
                ('schedule', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('online_type', models.CharField(blank=True, choices=[('Video Call', 'Video Call'), ('Voice Call', 'Voice Call'), ('Live Chat', 'Live Chat')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('emotion', models.CharField(max_length=100)),
                ('stress_level', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('completed', models.BooleanField(default=False)),
                ('tip_of_the_day', models.CharField(blank=True, max_length=255)),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('journaling_prompt', models.TextField(blank=True)),
                ('music_link', models.URLField(blank=True)),
                ('meditation_video', models.URLField(blank=True)),
                ('breathing_minutes', models.IntegerField(default=5)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tracker.recoverytracker')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField(blank=True, null=True)),
                ('voice_input', models.FileField(blank=True, null=True, upload_to='session_audios/')),
                ('video_input', models.FileField(blank=True, null=True, upload_to='session_videos/')),
                ('llm_emotion', models.CharField(blank=True, max_length=100, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=50, null=True)),
                ('time_of_analysis', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Video Call', 'Video Call'), ('Voice Call', 'Voice Call'), ('Chat', 'Chat')], max_length=20)),
                ('summary', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='TherapistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tracker.therapist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
