# Generated by Django 5.2 on 2025-09-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_activitylog_userdevice_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistreview',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='therapistreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='therapistreview',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_reviews', to='tracker.therapist'),
        ),
        migrations.AlterUniqueTogether(
            name='therapistreview',
            unique_together={('therapist', 'user')},
        ),
    ]
