# Generated by Django 5.2 on 2025-09-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_therapistreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='therapistreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='therapistreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='therapistreview',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tracker.therapist'),
        ),
    ]
