# Generated by Django 5.2 on 2025-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_create_therapist_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='availability_hours',
            new_name='availabilityhours',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='profile_img',
            new_name='profileimg',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='availability_mode',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='expertise_areas',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='profile_description',
        ),
        migrations.AddField(
            model_name='therapist',
            name='availabilitymode',
            field=models.CharField(default='both', max_length=50),
        ),
        migrations.AddField(
            model_name='therapist',
            name='expertiseareas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profiledescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specializations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
