# Generated by Django 5.2 on 2025-09-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_expertisearea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='assigned_expertise_areas',
            field=models.ManyToManyField(blank=True, related_name='therapist_assignments', to='tracker.expertisearea'),
        ),
        migrations.CreateModel(
            name='TherapistSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_specializations', to='tracker.therapist')),
            ],
            options={
                'unique_together': {('therapist', 'name')},
            },
        ),
    ]
