# Generated by Django 5.2 on 2025-09-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_journalentry_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslog',
            name='date',
        ),
    ]
