# Generated by Django 5.2 on 2025-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_progresslog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-09-21'),
            preserve_default=False,
        ),
    ]
