# Generated by Django 5.2 on 2025-09-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_progresslog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresslog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='progresslog',
            unique_together={('tracker', 'date')},
        ),
    ]
